### ISSUE TITLE
Two things

### ISSUE THREAD

**Issue by pjv** [luminous-devs/lume#115]
When trying to start Lume up over Tor I get this:

<img width="237" alt="SCR-20231120-iunn" src="https://github.com/luminous-devs/lume/assets/327716/9f41f384-0582-40ce-b1ca-29855363b189">

Two things:

1. Probably some back-end server somewhere is blocking tor exits. I think you shouldn’t block tor exits, though I also understand that evil people do evil things through Tor.
2. I think you shouldn’t block the app from working because you can’t check for updates - that seems like a bad decision.

**Comment by reyamir** [comment]
Hi, thank your feedback,
I totally agree with you, in the next update I will make auto-updater is optional, user can choose to enable in settings screen
and user can check for update manually

**Comment by reyamir** [comment]
I'm also found out why it not work with Tor, because my updater server run via Cloudflare Worker
I will move to self hosted later

**Comment by reyamir** [comment]
Hi, I've released a new version, https://github.com/luminous-devs/lume/releases/tag/v2.1.2
auto update is disabled by default now

**Comment by pjv** [comment]
Nice! - the app is working great over tor now. I’ll keep using and watch the app’s progress by updating manually until your update server gets re-homed. Thanks for doing this.
