### ISSUE TITLE
Releases link is not working

### ISSUE THREAD

**Issue by maxbrito500** [luminous-devs/lume#29]
Hello, I'm a linux user (Ubuntu 22.04) and the releases link from the main page is broken.

Also tried to find them here on the main repo but not available either.

It would be possible for me to install from the source code, but would of course prefer an "app experience" to just install and update like any other desktop tool.

Btw, when can lume be made available on the Ubuntu app store?

Many thanks, this looks like a fantastic nostr client!

**Comment by reyamir** [comment]
Thank you for appreciating my work, the current website is outdated. I'm working for release version 1.0 and it's not ready yet, if you want to try Lume, the only way is build from source or run dev build.

You can put your npub here, I will inform you when it ready. I'm also building a new website for waitlist, where everyone can put their npub or email (optional) to receive information about offical release

**Comment by IngwiePhoenix** [comment]
Was going to post an issue here too. Lume looks phenominal; somewhere between Element, Cinny and  and Nostrid. Really like the look of things!

Looking forward to running it on my PC (Windows). :)

**Comment by reyamir** [comment]
> Was going to post an issue here too. Lume looks phenominal; somewhere between Element, Cinny and and Nostrid. Really like the look of things!
> 
> Looking forward to running it on my PC (Windows). :)

Thank you for your kind words, I'm trying my best to release official version this month

**Comment by reyamir** [comment]
Yo new version is released https://github.com/luminous-devs/lume/releases/tag/v1.0.0

**Comment by IngwiePhoenix** [comment]
Testing it right now!

Wanted to shout you out properly, but it seems your `/.well-known/nostr.json` doesnt have your username in it (even when appending `?username=reya`).

Please do let me know your npub so I can follow you and stuff! 

Unironically, I had posted this just a few days ago: https://primal.net/thread/note10qmmhax0auygedyrxl7dvahzwcp4mkrahjq8k0892kkhehhmktdsw4h6wn

What I am missing so far is actually configuring my relays. Also on Windows, I am still shown the shortcuts for macOS; so I have to click things, for now :)
