### ISSUE TITLE
Improve the compose experience with text + images

### ISSUE THREAD

**Issue by dtonon** [luminous-devs/lume#36]
When adding one or more images they are forced at the bottom and the user can only add text above. Often it is useful to keep a proper order for text and images. The suggestion is to let the user to freely write above/below every image and also let him move (drag) the images around.

Another addition could be to let the user to visually reduce in the preview the image size from 100% width to 50%; this could be useful to make room to the text area, above all when dealing with vertical images.

**Comment by reyamir** [comment]
Thank for great idea 🔥, an enhancement compose will come with support long-form content and full-screen mode

**Comment by dtonon** [comment]
Yeah, the proposed enhancements are really important when dealing with the long format!
