### ISSUE TITLE
Unexpected application error when opening app

### ISSUE THREAD

**Issue by thetronjohnson** [luminous-devs/lume#47]
- OS: macOS Ventura 13.4.1
- Processor: Intel i5 (2020)
- App package: Lume 1.0.0 universal dmg

<img width="1192" alt="Screenshot 2023-07-08 at 4 19 39 PM" src="https://github.com/luminous-devs/lume/assets/22194802/21147719-3f13-42fd-8700-1e8da2688d3a">

**Comment by reyamir** [comment]
look strange, is restart app help?

**Comment by thetronjohnson** [comment]
did try that, but still the same error

**Comment by reyamir** [comment]
> did try that, but still the same error

hmm, I'll dig more

**Comment by thetronjohnson** [comment]
<img width="1192" alt="Screenshot 2023-07-08 at 6 56 41 PM" src="https://github.com/luminous-devs/lume/assets/22194802/6f80f8d3-9d0e-4165-a890-fca787333f3e">

Tried building this locally on the same machine and ran into this

However, I installed lume on a mac m2 and it works great! love the product ❤️

**Comment by reyamir** [comment]
thank you
I have more clue to debug

**Comment by thetronjohnson** [comment]
@reyamir update: release 1.0.1 is working on my i5 system
