### ISSUE TITLE
Remove plaintext password - the wizard appears to be stuck

### ISSUE THREAD

**Issue by dtonon** [luminous-devs/lume#51]
After clicking the button a green flag is showed, then I inserted the password, pressed enter and the wizard restarted.
So I closed and reopened the app and I was correctly prompted to insert a password, then all worked fine.

<img width="444" alt="Screenshot 2023-07-10 alle 10 11 58" src="https://github.com/luminous-devs/lume/assets/89577423/c2a6ace4-6c8d-41fd-8b88-23c4e270bac3">

**Comment by reyamir** [comment]
oh, I forgot clear cache remove plaintext privkey 😅. so the wizard start again, I will fix it asap

**Comment by dtonon** [comment]
I have a doubt: what happens if the user "Click to remove" but doesn't input the password and closes the app? If the steps are real as described, the password at that point is only in memory, and so the account should be reset.

**Comment by reyamir** [comment]
> I have a doubt: what happens if the user "Click to remove" but doesn't input the password and closes the app? If the steps are real as described, the password at that point is only in memory, and so the account should be reset.

if user close app, when they reopen, lume will auto redirect to unlock page (enter password), if no password user will stuck on this page

I will fix it

**Comment by reyamir** [comment]
ah this is a bug, you must set password in this step, if not set password (force quit), app won't work in next time

I'm working on improve UX for this page, I have 2 options

- Prevent user close app if not set password (show alert when user click close button)
- If user not set password close app, next time open app, it will auto redirect to `upgrade security` page again

**Comment by dtonon** [comment]
Ok, as I supposed :)

I suggest to remove the button, it is misleading and prevent to create an atomic procedure.
A simpler and effective solution is use a one step procedure:

---

You're using old Lume version which store your private key as plaintext in database, this is huge security risk.
To secure your private key set a password and Lume will put your private key in secure storage.

Set a password to protect your key
\______________________

[ Secure my nsec with a password  ]

---

When the user press the final button do the migration and open the password.
If the user close the window, quit the app and don't let him go on without the security migration.

**Comment by reyamir** [comment]
Thank for your suggestion
My update, I'm also added prevent close window, if user force quit, next time it will auto redirect to this page again

<img width="1192" alt="image" src="https://github.com/luminous-devs/lume/assets/123083837/29254ce8-572a-4740-9946-b6022b0a4201">

**Comment by dtonon** [comment]
Don't prevent the user to close the window, in this case simply close the app.

I would also remove "You must set the password before close app" text in that position, it is alarming without any real reason. Offer more details before:

_....
To secure your private key set a password and Lume will put your private key in secure storage.
It is not possible to start the app without applying this step, it is easy and fast!_

**Comment by reyamir** [comment]
I've updated it in latest build 🔥
