### ISSUE TITLE
App stops after few seconds

### ISSUE THREAD

**Issue by AleksandarIlic** [luminous-devs/lume#57]
- Generated new nsec without any signed events.
- Logged in with nsec.
- Set a password.
- Skipped posting lume note.
- Main screen loaded and after few seconds this happens:
<img width="514" alt="Screenshot 2023-07-21 at 11 08 36" src="https://github.com/luminous-devs/lume/assets/1103119/c3798cd1-06ce-43af-b84d-d6ef9fdea8fe">

The app was installed from Lume_1.0.1_aarch64.dmg on M1 computer.

**Comment by reyamir** [comment]
this cause by poor handle error from fetch request, I'm working on v1.1.0 which address a lot of errors cause app crash, maybe release in this weekend

**Comment by zerusty** [comment]
I got the same issue. stops loading after the initial screen.

**Comment by reyamir** [comment]
I will release v1.1.0 on Thursday which fix this issue 🔥
