### ISSUE TITLE
Lost test private key and can't reset

### ISSUE THREAD

**Issue by noubre** [luminous-devs/lume#62]
Hello,

I created a test private key to use with Lume, but I lost it. Deleting the App Image and re-downloading doesn't help. Where is the data stored and how can I delete/reset it?

Thanks!

**Comment by reyamir** [comment]
Hi, which os you are using?
before moving to secure storage (< v1.0.0), Lume stored your private key as plain-text in sqlite file, in folder `(macOS) /Users/<username>/Library/Aplication Support/com.lume.nu`, you can use any sql editor to view your key

**Comment by noubre** [comment]
I'm on Linux. Thanks!

**Comment by reyamir** [comment]
oh, on linux, you can check folder /etc/com.lume.nu

**Comment by reyamir** [comment]
but, I will improve onboarding/login process to make sure user save their keys before go to next step

**Comment by noubre** [comment]
Thanks!
