### ISSUE TITLE
Repost label gets hidden on trending posts

### ISSUE THREAD

**Issue by dragon-foobar** [luminous-devs/lume#64]
User story: As a lume user, I want to see what each action button on a post refers to. For example, I want to see clearly that the repost button is 'repost'. 

Currently the repost button gets hidden behind images, or has a strange opacity where there is a text post just above.

<img width="344" alt="Screen Shot 2023-08-07 at 8 43 40 am" src="https://github.com/luminous-devs/lume/assets/129810153/105a1ac6-873c-4dbc-aa92-e568a4e37eca">
<img width="351" alt="Screen Shot 2023-08-07 at 8 44 08 am" src="https://github.com/luminous-devs/lume/assets/129810153/7731157b-5dd7-4ba6-9c62-79e58c400c1a">

**Comment by dragon-foobar** [comment]
Actually seems to be same behaviour for other buttons too.

**Comment by reyamir** [comment]
I've fixed this issue in v1.2.0, it will be merged soon
