### ISSUE TITLE
App wont start. Lume 1.2.1 

### ISSUE THREAD

**Issue by Eternumkr** [luminous-devs/lume#81]
I downloaded  lume_1.2.1_amd64.deb and installed on ubuntu 22.04. app crashes immediately. 
there was a window that popped up once that asked if i wanted to send a report which i did but now it doesnt pop up anymore. there was some text that complained about a path.

**Comment by reyamir** [comment]
Hi
I've debugging it

**Comment by Eternumkr** [comment]
what is the fix?

**Comment by reyamir** [comment]
I'm still debugging, this issue happen only on Production, look like something wrong with `tauri build`

**Comment by Eternumkr** [comment]
oh. sorry i read that as "I've debugged it".

**Comment by reyamir** [comment]
ok, I've found the problem, I'm pushing new build, maybe take around 20 mins

**Comment by Eternumkr** [comment]
Awesome. ty.

**Comment by reyamir** [comment]
Hi, new build is out, can you help me re-test it? https://github.com/luminous-devs/lume/releases/tag/v1.2.1
just remove old build and install new build

**Comment by Eternumkr** [comment]
ok, uninstalled then reinstalled from the link via the deb file. no notable changes on ubuntu 22.04. still opens for a second then closes immediately. also tried the appimage as well.

**Comment by reyamir** [comment]
oh, look like different issues, I'll debug on Ubuntu and feedback to you

**Comment by Eternumkr** [comment]
so the crash window says the following,
"The application Lume has closed unexpectedly"
then goes into some more detail
"executable path"
/usr/bin/lume
"problem type"
Crash
"Title"
lume crashed with SIGABRT
"ApportVersion"
2.20.11-ubuntu82.5
"crash counter"
1
"JournalErrors"
Sep 04 xx:xx:xx My-Ubuntu gnome-shell[3195]:meta_window_set_stack_position_no_sync:assertion ' window->stack_position>=0' failed
"nonfreekernalmodules"
zfs zunicode zval icp zcommon znvpair
"Stacktrace"
alot of  "pthread_kill_internal" "no locals" "no symbol table info available" "

hope this helps a little.

**Comment by reyamir** [comment]
thank for detail report, I've installed Ubuntu on my machine, I'll debug it

**Comment by reyamir** [comment]
Hi @Eternumkr , I've pushed new version, can you help me try it?
you can completely remove old version before install new

**Comment by Eternumkr** [comment]
ok ill do that right now.

**Comment by Eternumkr** [comment]
JournalError: My-PC nautilus[8006]: Source ID 7357 was not found when attempting to remove it. 

Same sort of GUI crash, launched then after a second or so closed.

**Comment by reyamir** [comment]
I've tested Lume on dev build, it's work but not prob build 
I'm debugging it
