### ISSUE TITLE
AppImage menu has no Integrations > NWC

### ISSUE THREAD

**Issue by ok300** [luminous-devs/lume#89]
I've seen it in some screen recordings, but when I tried it with the latest AppImage, there is no Integrations menu section.

**Comment by reyamir** [comment]
ah, current latest build (v1.2.4) isn't have "Integration" yet, I will new build (v1.2.5) today or tomorrow which include "Integration" and improve onboarding process

**Comment by ok300** [comment]
Thank you sir!

**Comment by ok300** [comment]
Works in latest v1.2.5

**Comment by reyamir** [comment]
thank for using Lume, it still a bit of buggy, you shouldn't use real account for test 😅

**Comment by ok300** [comment]
Yes just tested for now, but looks promising!
