### ISSUE TITLE
App crashes seconds after opening.

### ISSUE THREAD

**Issue by gabrielmoura** [luminous-devs/lume#95]
Hello, I don't know how to solve this.
When opening the app after a few seconds it crashes.
Displays the feeds and allows login, but then crashes.

In a red box it displays:

> Can't find variable: React

And the console displays the text below.
```bash
$ ./lume_1.2.6_amd64.AppImage
Gtk-Message: 19:02:58.168: Failed to load module "xapp-gtk3-module"
Gtk-Message: 19:02:58.530: Failed to load module "xapp-gtk3-module"
Gtk-Message: 19:02:58.584: Failed to load module "xapp-gtk3-module"
Asset `splashscreen` not found; fallback to splashscreen.html

** (lume:1153055): WARNING **: 19:03:23.508: atk-bridge: get_device_events_reply: unknown signature
```

**Comment by reyamir** [comment]
Hi, you can update to v1.2.7 to fix this issue https://github.com/luminous-devs/lume/releases/tag/v1.2.7
but look like auto-updater not working on your machine, I will check it

**Comment by gabrielmoura** [comment]
Thank you very much, this solved my problem.
